### ISSUE TITLE
Rich presence for Discord & Steam

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#11]
It should include the player's status, how long they've been playing and how many people are in their lobby (if they are in one).

- [x] Discord
- [x] Steam

**Comment by hermitec** [comment]
Discord RP at least I know I can do, steam presence idk hopefully I'll figure it out

**Comment by JoshPiper** [comment]
https://partner.steamgames.com/doc/features/enhancedrichpresence

https://wiki.facepunch.com/steamworks/SteamFriends.SetRichPresence
https://wiki.facepunch.com/steamworks/SteamFriends.GetRichPresence
probably the methods you want?

**Comment by GlorifiedPig** [comment]
> 
> 
> Discord RP at least I know I can do, steam presence idk hopefully I'll figure it out

Steam is easy as well with Facepunch.Steamworks, it does require a language JSON uploaded to the site though, so we'll have to be creative and come up with a few things

**Comment by hermitec** [comment]
Let it be known that derek did basically all the discord rich presence code for me
