### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#12]
We should make a manager for version control. This could also be used when initializing server lobbies to prevent people who are out of date from joining.

**Comment by hermitec** [comment]
Version is kept in NetManager, has to be set manually cause idk a better way of doing it. #51 Lobbies are autodestroyed if version mismatch is detected (though this is done in a semi-ugly way i dont think it really matters since the main menu isnt particularly resource intensive anyway)

**Comment by GlorifiedPig** [comment]
> 
> 
> Version is kept in NetManager, has to be set manually cause idk a better way of doing it. #51 Lobbies are autodestroyed if version mismatch is detected (though this is done in a semi-ugly way i dont think it really matters since the main menu isnt particularly resource intensive anyway)

Why the fuck is it in NetManager? It's not going to be networked bruh

**Comment by hermitec** [comment]
> 
> 
> > Version is kept in NetManager, has to be set manually cause idk a better way of doing it. #51 Lobbies are autodestroyed if version mismatch is detected (though this is done in a semi-ugly way i dont think it really matters since the main menu isnt particularly resource intensive anyway)
> 
> Why the fuck is it in NetManager? It's not going to be networked bruh

pretty sure i told you this is just a temporary measure and not the final way of doing it, my bad if you got confused cause i closed the issue

**Comment by JoshPiper** [comment]
SHA / version are kept in the Constants/VersionManager.cs
This is set to a default value if not found, but is set during the build pipeline for steam deployments.

Is this all complete @hermitec @GlorifiedPig?

**Comment by GlorifiedPig** [comment]
Completed but don't dare look at the file
