### ISSUE TITLE
Chat text outline

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#22]
https://external-preview.redd.it/5fygtKo0YS7P7Vai49Cab_MBZAtgJQwxR7bga5k5bdg.png?auto=webp&s=2b21d5ad25c2d23fa5481ec57811a381acbe706d

**Comment by JoshPiper** [comment]
Marking this as an issue rather than a request, since it effects accessability.

**Comment by JoshPiper** [comment]
Removed from milestone, it's extremely useful, but shouldn't block the 1.0 date.
