### ISSUE TITLE
Improve chat antispam

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#25]
In my opinion, 3 seconds is a bit long, I like to send messages quite fast. We should make it so if they send 3 messages in a timespan of 4 or less seconds, then we should add the timer for the next message.

**Comment by GlorifiedPig** [comment]
Another thing recently noticed: even if you press enter with an empty message the anti spam timer still occurs.

**Comment by JoshPiper** [comment]
Removed from milestone. Again, good improvement to have, but even e-sports titles like cs:go and r6s don't have antispam, so can just be removed to prevent 1.0 block.
