### ISSUE TITLE
Variable to store that the player is the host on the PlayerNetworking class

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#26]
Side-note: We could also display "HOST" under the ping section in the scoreboard instead of that ugly 0.

**Comment by JoshPiper** [comment]
Would it not work to make 0 ping automatically display host?

**Comment by GlorifiedPig** [comment]
> 
> 
> Would it not work to make 0 ping automatically display host?

cheese strat, we'll use the boolean for other things (and ping and networking is handled in different scripts too so it'll be more difficult)
