### ISSUE TITLE
Role tags in chat and overhead display

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#28]
Certain SteamIDs could have the Developer, Moderator and Tester tags.

**Comment by JoshPiper** [comment]
I don't think Mod should be called mod, since that might be confusing for people who think they are in-game mods.

**Comment by JoshPiper** [comment]
I've seen this in the source, is this fully implemented @GlorifiedPig @hermitec?
