### ISSUE TITLE
Lobby browser

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#29]

**Comment by hermitec** [comment]
taking a look, seeing what i can do 👁️ 👁️ 
(no promises)

**Comment by hermitec** [comment]
doesnt actually look like this would be too difficult PauseChamp

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104812284-1f633280-57f9-11eb-85c7-df2909e98177.png)
first draft of lobby prefab, actual thing will obviously have metadata like lobby name etc, but i want to get the backend working first

**Comment by hermitec** [comment]
ok backend works :)

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104815749-55f77800-580e-11eb-860e-c95024867045.png)
progress report, backend is done and everything basically works now i just need to add a refresh button and the initial commit is good (will add metadata / qol stuff later)

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104816001-20538e80-5810-11eb-96d7-75dfd6b3dad4.png)
initial version done

**Comment by hermitec** [comment]
not yet snake, it's not over yet

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104822439-69b8d380-583a-11eb-9435-992edf9c7fbe.png)
fix for the disappearing lobby name bug, i also completely reworked the way lobby names are allocated so it will be much easier to allow users to make custom lobby names in future (now uses lobbydata instead of just getting the owner's steam name)

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104822702-66bee280-583c-11eb-9791-9c3acacc0509.png)
people are probably going to see this one a lot

**Comment by GlorifiedPig** [comment]
maybe change "open" to "public"

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104822731-9ec62580-583c-11eb-8926-09eb55e7f2b1.png)
subtle psychological trick, i like it

**Comment by GlorifiedPig** [comment]
oh yeah, also make sure to add "and make sure your internet connection is okay"

**Comment by hermitec** [comment]
anything else master?

**Comment by GlorifiedPig** [comment]
> anything else master?

make the refresh button bigger because jesus those borders

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104822809-480d1b80-583d-11eb-9f01-023e73d6560b.png)


> 
> 
> > anything else master?
> 
> make the refresh button bigger because jesus those borders

keep in mind it looks extra fucky because im screencapping from the editor, not the actual game window. still made it slightly bigger anyway

**Comment by hermitec** [comment]
gonna make it bigger still hold up

**Comment by GlorifiedPig** [comment]
> ![image](https://user-images.githubusercontent.com/63280379/104822809-480d1b80-583d-11eb-9f01-023e73d6560b.png)
> 
> > > anything else master?
> > 
> > 
> > make the refresh button bigger because jesus those borders
> 
> keep in mind it looks extra fucky because im screencapping from the editor, not the actual game window. still made it slightly bigger anyway

Yeah I understand that don't worry, but the refresh button was fucking tiny either way
Mother of quotes though this is fucking the discord webhook up

**Comment by hermitec** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/63280379/104822809-480d1b80-583d-11eb-9f01-023e73d6560b.png)
> > > > anything else master?
> > > 
> > > 
> > > make the refresh button bigger because jesus those borders
> > 
> > 
> > keep in mind it looks extra fucky because im screencapping from the editor, not the actual game window. still made it slightly bigger anyway
> 
> Yeah I understand that don't worry, but the refresh button was fucking tiny either way
> Mother of quotes though this is fucking the discord webhook up

too late to stop now 
![image](https://user-images.githubusercontent.com/63280379/104822866-96bab580-583d-11eb-861f-be78afa21c66.png)

**Comment by GlorifiedPig** [comment]
![image](https://user-images.githubusercontent.com/7416288/104822925-caeaa200-584e-11eb-9336-886ee94fc2ea.png)
Fixed

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104823106-86a3d580-583f-11eb-843e-fb3d5fa2d873.png)

**Comment by hermitec** [comment]
alright this isnt done but the core functionality is there im just gonna close this for now so it counts towards the 0.1 milestone

**Comment by GlorifiedPig** [comment]
Wait I need to keep it open as a reminder to optimize

**Comment by GlorifiedPig** [comment]
Right I've optimized and changed the bit I've seen, can't really complain the code actually looks pretty good, nice job
