### ISSUE TITLE
Dead players don't go invisible to alive players

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#39]
Dead players are supposed to be invisible & have disabled collisions with alive players, but alive players see them as regular players; and dead players see them how they should.

**Comment by Derek-R-S** [comment]
Fixed in [this commit](https://github.com/GlorifiedStudios/Catch-Me-If-You-Can/commit/e1bb911cd1f37e6020d72804ca08355080e37cf2)
