### ISSUE TITLE
Add display for winner of the round

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#43]

**Comment by hermitec** [comment]
ok

**Comment by hermitec** [comment]
ok so i've made a multipurpose text box that hangs at the extreme-middle-bottom-middle of the screen 
![image](https://user-images.githubusercontent.com/63280379/104730242-97febc00-5731-11eb-80e5-be1cf2823126.png)
obviously can be used for this but can maybe be used for other notifications in future like join/leave or overall game win/loss

**Comment by hermitec** [comment]
will work on a basic API for posting/expiring messages alongside this issue

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/104732285-e497c680-5734-11eb-8c2a-f5b872264d26.png)
your boy about to close two issues at once

**Comment by GlorifiedPig** [comment]
cool, is it animated
it looks 3d like it rotates

**Comment by GlorifiedPig** [comment]
didnt mnean to close

**Comment by hermitec** [comment]
tested and this works

**Comment by hermitec** [comment]
> 
> 
> cool, is it animated
> it looks 3d like it rotates

no lol its text like the rest of the UI

**Comment by GlorifiedPig** [comment]
> 
> 
> > cool, is it animated
> > it looks 3d like it rotates
> 
> no lol its text like the rest of the UI

the rest of the UI fucking rotates

**Comment by hermitec** [comment]
> 
> 
> > > cool, is it animated
> > > it looks 3d like it rotates
> > 
> > 
> > no lol its text like the rest of the UI
> 
> the rest of the UI fucking rotates

oh you mean like that thats not rotating thats motion stuff yeah it does that duh
