### ISSUE TITLE
Server settings

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#45]
- [x] Map
- [x] Friends Only
- [x] Max Players
- [x] Round Time
- [x] Tickrate
- [x] Tag Delay
- [x] Speed Multiplier
- [x] Gravity Multiplier
- [x] Energy Regen
- [x] Wall Bounciness
- [x] Auto Jump

**Comment by hermitec** [comment]
🔴 im probably not doing all of this at least not in good time there's a lot to implement here 🔴 
but i'll make a start

**Comment by hermitec** [comment]
is tickrate really necessary to include in server settings? are there issues with worse connections using a higher tickrate?

**Comment by GlorifiedPig** [comment]
> is tickrate really necessary to include in server settings? are there issues with worse connections using a higher tickrate?

Definitely, the host player's tickrate is limited to his FPS, and if it's 64tick but the host player has shit internet and fluctuating FPS between like 30 and 60 it's going to start becoming inconsistent

Plus it'd make the game less laggy for people overseas on 32 tick, and reduce network usage, and reduce framerate usage

If it's a group of friends playing locally with OK PCs then they have the option of 64 tick, but most hosts might not

**Comment by GlorifiedPig** [comment]
This is done & implemented
