### ISSUE TITLE
Pre-release gadget master list

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#50]
- [x] Grappling hook
- [ ] Anti-gravity gun, which turns gravity upside down as long as it's active and there's enough energy (terraria moment)
- [ ] Waypoint placer & teleporter
- [ ] Tractor beam (ability to push & pull other players) - energy consumption much higher
- [ ] "Pegasus Boots" which allow you to have less gravity upon jumping, wall running and more overall speed, and cool particle effects, maybe it could also allow Source Engine-esque bunnyhopping
- [ ] Gun that shoots a projectile, and you teleport wherever that projectile lands

**Comment by GlorifiedPig** [comment]
Requesting opinions on these gadgets @hermitec @TrollOfAllTrolls @JoshPiper

**Comment by JoshPiper** [comment]
looks good

**Comment by hermitec** [comment]
1) sounds interesting
2) i think that would be way too confusing especially for new players, would seem like BS
3) sounds good
4) maybe with very limited charge
5) pegasus boots sounds cool with limited duration

**Comment by GlorifiedPig** [comment]
> 
> 
>     1. sounds interesting
> 
>     2. i think that would be way too confusing especially for new players, would seem like BS
> 
>     3. sounds good
> 
>     4. maybe with very limited charge
> 
>     5. pegasus boots sounds cool with limited duration

cool, probably going to go with these suggestions

**Comment by JoshPiper** [comment]
Removed from milestone, pinned instead.
