### ISSUE TITLE
Lobby metadata

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#51]
- [x] Version number to prevent people joining lobbies with the wrong version
- [x] Map

This should be updated when server settings is done. That takes priority as we need that to add all the settings to the metadata too

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/105166255-2f3b8900-5b0f-11eb-8185-6f728362c59d.png)
running out of space on the lobby browser entries

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/105169976-31ecad00-5b14-11eb-9561-8751392246d1.png)
actually fetches map name now lol

**Comment by hermitec** [comment]
how do we want version number to be stored?

**Comment by GlorifiedPig** [comment]
> how do we want version number to be stored?

See #12

**Comment by hermitec** [comment]
see #12

**Comment by GlorifiedPig** [comment]
Re-opening because server settings still needs to be done for appropriate filtering
