### ISSUE TITLE
Lobby UI is not done correctly

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#52]
I know Benjamin did a workaround and I assume that's what's fucking with it since it's not consistent with EasyButton's other UI components.
![](https://cdn.discordapp.com/attachments/797201389461569586/801160803461103636/unknown.png)

- The display looks funny as seen above on smaller resolutions.
- Sometimes the "click radius" is slightly higher than the button itself, making you need to offset your mouse.

**Comment by GlorifiedPig** [comment]
@hermitec Did you fix

**Comment by hermitec** [comment]
> @hermitec Did you fix

yes and it had fuck all to do with my workaround im actually a lazy UI designer and the no. of players text was overlapping with the button clickbox but my **coding genius** is still intact
