### ISSUE TITLE
Countdown bug

### ISSUE THREAD

**Issue by CaspiaLeafeon** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#57]
Heya, Discord user Caspia#9472 here, found a new little issue. 

When all players leave the match with the round start countdown beginning, the countdown doesnt reset, and the eternal ticking that threatens my sanity doesnt stop. Not to mention, once someone joins the countdown automatically resumes, which could have rounds instantly start if the countdown was left with only one second remaining. Its not a huge bug, though if theres only one player in a lobby, I feel the countdown should automaticially reset so the eternal ticking can end and let my sanity return.

**Comment by GlorifiedPig** [comment]
Fixed in 4efc4ae, thanks for reporting :)
