### ISSUE TITLE
Localization manager

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#9]
We should have all languages and their appropriate texts stored somewhere, and also a script where you are able to set a variable to be a certain TMP Text object, and the text updates appropriately to the configured language key.

**Comment by hermitec** [comment]
are we really doing this again
multibombers flashbacks

**Comment by GlorifiedPig** [comment]
> 
> 
> are we really doing this again
> multibombers flashbacks

i actually have a really good plan in mind for this, using a localization key instead of localizing every single string for every script attached, you'll see what i mean when i do it

**Comment by GlorifiedPig** [comment]
The manager itself is done as well as a few other useful classes, however, most phrases actually need to be converted

I'll close this now though since it's done
